model_name: eegnex
seed: 45
optuna_objective: composite_min_f1_plur_corr
min_f1_threshold: 37.0
save_ckpt: true

# Data sources (relative)
materialized_dir: data_preprocessed/hpf_1.5_lpf_35_baseline-on-avgref
crop_ms: [0, 496]
exclude_channel_list: non_scalp
trial_filter: acc1           # 'all' (default) or 'acc1' to keep only accurate trials
# trial_filter_acc_column: Target.ACC  # override if your accuracy column name differs

# Training
batch_size: 8
lr: 0.0007
epochs: 40
early_stop: 10
inner_n_folds: 5
n_folds: 6

outer_eval_mode: ensemble

