# Title: Stage 1B - Light Augmentation Probe
# --- Training budget ---
epochs:
  method: int
  low: 50
  high: 70
early_stop:
  method: int
  low: 10
  high: 14
batch_size:
  method: categorical
  choices: [8]

# --- Optimizer / scheduler (FIXED from Step 1A winner) ---
lr:
  method: categorical
  choices: [7.0e-5]
weight_decay:
  method: categorical
  choices: [0.0]
scheduler_patience:
  method: categorical
  choices: [10]

# --- Stabilizers (FIXED from Step 1A winner) ---
drop_prob:
  method: categorical
  choices: [0.55]
lr_warmup_frac:
  method: categorical
  choices: [0.0]
lr_warmup_init:
  method: categorical
  choices: [0.3]

# --- Architecture (FIXED from Step 1A winner) ---
filter_1:
  method: categorical
  choices: [21]
filter_2:
  method: categorical
  choices: [49]
kernel_block_1_2:
  method: categorical
  choices: [68]
kernel_block_4:
  method: categorical
  choices: [39]
kernel_block_5:
  method: categorical
  choices: [21]
avg_pool_block4:
  method: categorical
  choices: [6]
avg_pool_block5:
  method: categorical
  choices: [6]
dilation_block_4:
  method: categorical
  choices: [3]
dilation_block_5:
  method: categorical
  choices: [5]
depth_multiplier:
  method: categorical
  choices: [3]
activation:
  method: categorical
  choices: [elu]
max_norm_conv:
  method: categorical
  choices: [2.015126268370284]
max_norm_linear:
  method: categorical
  choices: [0.49732734465090944]

# --- Light augmentation SEARCH ---
mixup_alpha:
  method: uniform
  low: 0.0
  high: 0.15

shift_p:
  method: uniform
  low: 0.0
  high: 0.20
shift_max_frac:
  method: uniform
  low: 0.0
  high: 0.03

noise_p:
  method: uniform
  low: 0.0
  high: 0.20
noise_std:
  method: uniform
  low: 0.002
  high: 0.010

time_mask_p:
  method: uniform
  low: 0.0
  high: 0.20
time_mask_frac:
  method: uniform
  low: 0.02
  high: 0.08

# Keep these OFF
scale_p:
  method: categorical
  choices: [0.0]
scale_min:
  method: categorical
  choices: [1.0]
scale_max:
  method: categorical
  choices: [1.0]
chan_mask_p:
  method: categorical
  choices: [0.0]
chan_mask_ratio:
  method: categorical
  choices: [0.0]

# Aug warmup
aug_warmup_frac:
  method: uniform
  low: 0.10
  high: 0.30