model_name: eegnex

# Data sources (relative)
# materialized_dir: "data_preprocessed/hpf_1.0_lpf_45_baseline-on-example"

crop_ms: [0, 496]               # e.g., [0, 496]
use_channel_list: non_scalp      # e.g., non_scalp

# Training
batch_size: 8
lr: 0.0007
epochs: 40
early_stop: 10
inner_n_folds: 5
n_folds: 6
