model_name: eegnex
seed: 44
optuna_objective: composite_min_f1_diag_dom  # Composite: always balance min F1 (decodability) and diagonal dominance (distinctness)
composite_min_f1_weight: 0.65  # 65% weight on min F1 (ensures all classes decodable), 35% on diagonal dominance
save_ckpt: true
# Data sources (relative)
materialized_dir: data_preprocessed/hpf_1.5_lpf_40_baseline-off
crop_ms: [0, 400]               # e.g., [0, 496]
exclude_channel_list: non_scalp  # Exclude non-scalp channels

# Training
batch_size: 8
lr: 0.0007
epochs: 40
early_stop: 10
inner_n_folds: 5
n_folds: 6

outer_eval_mode: ensemble
# --- Refit Mode Controls (only used if outer_eval_mode: refit) ---
refit_val_k: 0            # 0 → train on all outer-train (no early stop); set >=2 for deterministic GroupKFold val
refit_early_stop: 10      # Patience for refit early stopping (if val is enabled)