# Controller for Step 1 search
subset_n: 5     # number of subjects to use (24 = all)
# n_folds: 1     # REMOVED to use LOSO, per Borra protocol
max_folds: 5     # cap LOSO to 3 folds during search for speed
epochs: 40
early_stop: 8
batch_size: 16
save_ckpt: true
random_state: 42

use_ica: true

