# XAI Default Configuration
# These parameters control the XAI reporting system behavior

# Peak window analysis
peak_window_ms: 100  # Duration of temporal window around each peak (milliseconds)

# Top-K channel labeling
xai_top_k_channels: 10  # Number of top channels to label in topomaps

# Time-frequency analysis (Morlet wavelet)
tf_morlet_freqs: [4, 8, 13, 30]  # Frequency bins for time-frequency decomposition (Hz)
