model_name: eegnex
seed: 1000
optuna_objective: inner_mean_min_per_class_f1

# Data sources (relative)
materialized_dir: data_preprocessed/hpf_1.5_lpf_40_baseline-off
crop_ms: [0, 496]               # e.g., [0, 496]
use_channel_list: non_scalp      # e.g., non_scalp. using "non_scalp" means exclude non-scalp channels

# Training
batch_size: 8
lr: 0.0007
epochs: 40
early_stop: 10
inner_n_folds: 5
n_folds: 6

outer_eval_mode: ensemble
# --- Refit Mode Controls (only used if outer_eval_mode: refit) ---
refit_val_k: 0            # 0 → train on all outer-train (no early stop); set >=2 for deterministic GroupKFold val
refit_early_stop: 10      # Patience for refit early stopping (if val is enabled)