model_name: eegnex

# Data sources (relative)
# materialized_dir: "data_preprocessed/hpf_1.0_lpf_45_baseline-on-example"

crop_ms: [0, 496]               # e.g., [0, 496]
use_channel_list: non_scalp      # e.g., non_scalp

# Training
batch_size: 8
lr: 0.0007
epochs: 40
early_stop: 10
inner_n_folds: 5
n_folds: 6


# Outer test evaluation mode:
# - ensemble: average softmax across inner K models (default, variance-reducing)
# - refit: refit one model on outer-train (optionally with a small val split) and test once
outer_eval_mode: ensemble
# Optional refit controls (used only if outer_eval_mode: refit)
refit_val_frac: 0.0       # 0.0 → train on all outer-train; no early stopping
refit_early_stop: 10