# === DATASET CHOICE (REFINED based on previous results) ===
# We will test the top 4 performing dataset types from the last study.
materialized_dir:
  method: categorical
  choices:
    - data_preprocessed/hpf_1.5_lpf_35_baseline-off
    - data_preprocessed/hpf_1.5_lpf_40_baseline-off

# === CORE ARCHITECTURE WIDTHS (Ranges refined from results) ===
filter_1:         { method: int, low: 16,  high: 24 }
filter_2:         { method: int, low: 30, high: 55 }

# === LATE-BLOCK KERNEL SIZES (Ranges refined from results) ===
kernel_block_4:   { method: int, low: 28,  high: 48 }
kernel_block_5:   { method: int, low: 20,  high: 28 }

# === POOLING / DILATION (Unchanged for Step 1) ===
avg_pool_block4:  { method: int, low: 2,  high: 4 }
dilation_block_4: { method: int, low: 2,  high: 3 }

# === OPTIMIZATION / REGULARIZATION (BIG LEVERS - REFINED & EXPANDED) ===
# activation: { method: categorical, choices: [elu] }      
lr:         { method: log_uniform, low: 7.0e-5, high: 9.0e-4 }      # Expanded upper range
# batch_size: { method: categorical, choices: [8, 16] }             # Removed 32
drop_prob:  { method: uniform, low: 0.5, high: 0.8 }             # REFINED to focus on lower values
weight_decay: { method: log_uniform, low: 1.0e-5, high: 1.0e-2 } # ADDED: Critical new parameter

