# === REFINEMENT & STABILITY KNOBS (For Step 2) ===
# NOTE: This search should be run AFTER choosing the single best dataset
# and fixing the best parameters found in the Step 1 search.

# Late-block pooling / dilation
avg_pool_block5:    { method: int, low: 4,  high: 10 }
dilation_block_5:   { method: int, low: 1,  high: 6 }

# Finer architectural details
depth_multiplier:   { method: int, low: 1, high: 3 }      # ADDED: Important architectural knob
kernel_block_1_2:   { method: int, low: 16, high: 64 }

# Advanced regularization
max_norm_conv:      { method: uniform, low: 0.5, high: 2.5 }   # Expanded range slightly
max_norm_linear:    { method: uniform, low: 0.1, high: 0.8 }   # Expanded range slightly
scheduler_patience: { method: int, low: 3, high: 8 }