seeds: [44, 45]
epochs: 40
early_stop: 8
inner_val_frac: 0.2
save_ckpt: true
batch_size: 8
lr: 0.0003677427388250912
crop_ms:
- 0
- 496
use_channel_list: non_scalp
include_channels: null
channel_lists:
  non_scalp:
  - E1
  - E8
  - E14
  - E17
  - E21
  - E25
  - E32
  - E38
  - E44
  - E49
  - E56
  - E63
  - E68
  - E73
  - E81
  - E88
  - E94
  - E99
  - E107
  - E113
  - E114
  - E119
  - E120
  - E121
  - E125
  - E126
  - E127
  - E128
cz_step: 0
model_name: eegnex
inner_n_folds: 5
n_folds: null
refit_val_k: 0
refit_early_stop: 10
max_folds: null
random_state: 42
activation: elu
outer_eval_mode: ensemble
materialized_dir: data_preprocessed/hpf_1.5_lpf_35_baseline-off
filter_1: 18
filter_2: 44
kernel_block_4: 35
kernel_block_5: 24
avg_pool_block4: 3
dilation_block_4: 2
drop_prob: 0.6092420486428096
weight_decay: 0.005422750192203312
task: cardinality_1_3
