seed: 42
epochs: 40
early_stop: 8
inner_val_frac: 0.2
save_ckpt: true
batch_size: 8
lr: 0.00039399232014824615
crop_ms:
- 0
- 496
use_channel_list: non_scalp
include_channels: null
channel_lists:
  non_scalp:
  - E1
  - E8
  - E14
  - E17
  - E21
  - E25
  - E32
  - E38
  - E44
  - E49
  - E56
  - E63
  - E68
  - E73
  - E81
  - E88
  - E94
  - E99
  - E107
  - E113
  - E114
  - E119
  - E120
  - E121
  - E125
  - E126
  - E127
  - E128
cz_step: 0
model_name: eegnex
inner_n_folds: 5
n_folds: null
outer_eval_mode: ensemble
refit_val_frac: 0.0
refit_early_stop: 10
max_folds: null
random_state: 42
activation: elu
materialized_dir: data_preprocessed/hpf_1.5_lpf_40_baseline-off
filter_1: 24
filter_2: 38
kernel_block_4: 28
kernel_block_5: 24
avg_pool_block4: 3
dilation_block_4: 2
drop_prob: 0.5214851448432087
weight_decay: 0.0017813097926156977
task: cardinality_1_3
